-intstyle "ise" -incremental -o "Z:/Lista de Exercicios/EX1/tb_COMPARADOR_DE_FUNCOES_isim_beh.exe" -prj "Z:/Lista de Exercicios/EX1/tb_COMPARADOR_DE_FUNCOES_beh.prj" "work.tb_COMPARADOR_DE_FUNCOES" 
